import json
from pathlib import Path

import numpy as np
from sentence_transformers import SentenceTransformer


EVALUATION_PATH = Path(
    "data/vectorstore/retrieval_evaluation.json"
)

MODEL_NAME = "all-MiniLM-L6-v2"

OUTPUT_PATH = Path(
    "data/vectorstore/context_relevancy_evaluation.json"
)


def cosine_similarity(a, b):
    """
    Calculate cosine similarity between two vectors.

    The embeddings generated by SentenceTransformer
    are normalized, so this is equivalent to a dot product.
    """

    return float(
        np.dot(a, b)
    )


def main():

    print("=" * 80)
    print("NOVATEL CONTEXTUAL RELEVANCY EVALUATION")
    print("=" * 80)

    # --------------------------------------------------
    # Load retrieval evaluation
    # --------------------------------------------------

    with open(
        EVALUATION_PATH,
        "r",
        encoding="utf-8"
    ) as f:

        evaluation = json.load(f)

    results = evaluation["results"]

    # --------------------------------------------------
    # Load embedding model
    # --------------------------------------------------

    print()
    print("Loading embedding model...")

    model = SentenceTransformer(
        MODEL_NAME,
        local_files_only=True
    )

    print(
        "Benchmark questions:",
        len(results)
    )

    # --------------------------------------------------
    # Aggregate metrics
    # --------------------------------------------------

    relevancy_at_1_total = 0.0
    relevancy_at_3_total = 0.0
    relevancy_at_5_total = 0.0

    evaluated_results = []

    # --------------------------------------------------
    # Evaluate each question
    # --------------------------------------------------

    for result in results:

        question = result["question"]

        retrieved_chunks = result["top5"]

        # --------------------------------------------------
        # Encode question
        # --------------------------------------------------

        question_embedding = model.encode(
            question,
            convert_to_numpy=True,
            normalize_embeddings=True
        ).astype("float32")

        contexts = [
            chunk["text"]
            for chunk in retrieved_chunks
            if "text" in chunk
        ]

        # --------------------------------------------------
        # IMPORTANT:
        # Existing retrieval_evaluation.json currently
        # stores metadata but not the actual chunk text.
        # --------------------------------------------------

        if not contexts:

            evaluated_results.append(
                {
                    "question_id":
                        result["question_id"],

                    "question":
                        question,

                    "context_relevancy_at_1":
                        None,

                    "context_relevancy_at_3":
                        None,

                    "context_relevancy_at_5":
                        None
                }
            )

            continue

        # --------------------------------------------------
        # Encode retrieved contexts
        # --------------------------------------------------

        context_embeddings = model.encode(
            contexts,
            convert_to_numpy=True,
            normalize_embeddings=True
        ).astype("float32")

        scores = []

        for context_embedding in context_embeddings:

            score = cosine_similarity(
                question_embedding,
                context_embedding
            )

            scores.append(score)

        # --------------------------------------------------
        # Calculate average contextual relevancy
        # --------------------------------------------------

        relevancy_1 = (
            float(np.mean(scores[:1]))
            if len(scores) >= 1
            else 0.0
        )

        relevancy_3 = (
            float(np.mean(scores[:3]))
            if len(scores) >= 3
            else float(np.mean(scores))
        )

        relevancy_5 = (
            float(np.mean(scores[:5]))
            if len(scores) >= 5
            else float(np.mean(scores))
        )

        relevancy_at_1_total += relevancy_1
        relevancy_at_3_total += relevancy_3
        relevancy_at_5_total += relevancy_5

        evaluated_results.append(
            {
                "question_id":
                    result["question_id"],

                "category":
                    result["category"],

                "question":
                    question,

                "context_scores":
                    scores,

                "context_relevancy_at_1":
                    relevancy_1,

                "context_relevancy_at_3":
                    relevancy_3,

                "context_relevancy_at_5":
                    relevancy_5
            }
        )

    total = len(results)

    # --------------------------------------------------
    # Overall metrics
    # --------------------------------------------------

    contextual_relevancy_at_1 = (
        relevancy_at_1_total / total
    )

    contextual_relevancy_at_3 = (
        relevancy_at_3_total / total
    )

    contextual_relevancy_at_5 = (
        relevancy_at_5_total / total
    )

    # --------------------------------------------------
    # Print results
    # --------------------------------------------------

    print()
    print("=" * 80)
    print("CONTEXTUAL RELEVANCY RESULTS")
    print("=" * 80)

    print(
        f"Contextual Relevancy@1: "
        f"{contextual_relevancy_at_1:.4f}"
    )

    print(
        f"Contextual Relevancy@3: "
        f"{contextual_relevancy_at_3:.4f}"
    )

    print(
        f"Contextual Relevancy@5: "
        f"{contextual_relevancy_at_5:.4f}"
    )

    print()
    print(
        "Percentage representation:"
    )

    print(
        f"@1: "
        f"{contextual_relevancy_at_1 * 100:.2f}%"
    )

    print(
        f"@3: "
        f"{contextual_relevancy_at_3 * 100:.2f}%"
    )

    print(
        f"@5: "
        f"{contextual_relevancy_at_5 * 100:.2f}%"
    )

    # --------------------------------------------------
    # Per-question results
    # --------------------------------------------------

    print()
    print("=" * 80)
    print("PER-QUESTION CONTEXTUAL RELEVANCY")
    print("=" * 80)

    for result in evaluated_results:

        score = result[
            "context_relevancy_at_5"
        ]

        if score is None:

            print(
                f"{result['question_id']} | "
                f"No context text available"
            )

        else:

            print(
                f"{result['question_id']} | "
                f"C{result['category'][1:]} | "
                f"@1: "
                f"{result['context_relevancy_at_1']:.4f} | "
                f"@3: "
                f"{result['context_relevancy_at_3']:.4f} | "
                f"@5: "
                f"{result['context_relevancy_at_5']:.4f}"
            )

    # --------------------------------------------------
    # Save results
    # --------------------------------------------------

    with open(
        OUTPUT_PATH,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            {
                "total_questions":
                    total,

                "method":
                    "Embedding-based contextual relevancy "
                    "using all-MiniLM-L6-v2 cosine similarity",

                "metrics":
                    {
                        "contextual_relevancy_at_1":
                            contextual_relevancy_at_1,

                        "contextual_relevancy_at_3":
                            contextual_relevancy_at_3,

                        "contextual_relevancy_at_5":
                            contextual_relevancy_at_5
                    },

                "results":
                    evaluated_results
            },
            f,
            indent=2,
            ensure_ascii=False
        )

    print()
    print(
        "Evaluation saved to:",
        OUTPUT_PATH
    )


if __name__ == "__main__":
    main()